FROM oven/bun:latest

WORKDIR /usr/src/app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
ENV NODE_ENV=production
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install
RUN bun db:generate
# Build only the web app to avoid monorepo-wide build issues
RUN cd apps/web && bun run build


EXPOSE 3000

CMD ["bun", "run", "start:web"]
